[package]
name        = "aetherion_shared"
version     = "0.1.0"
edition     = "2021"
description = "Shared types, traits, and utilities for AetherionEngine modules"
license     = "MIT"

[dependencies]
# Core utilities (all pulled from workspace for consistency)
chrono      = { workspace = true }   # timestamps if needed
serde       = { workspace = true }
serde_json  = { workspace = true }
log         = { workspace = true }
thiserror   = { workspace = true }
rand        = { workspace = true }
once_cell   = { workspace = true }
lazy_static = { workspace = true }
rayon       = { workspace = true }   # always on for parallel iterators
