// ssxl_godot/src/engine/mod.rs
//
// Mythic core: zero root files, perfect separation.
// Every concern lives in its own file. This is the only thing
// that touches the outside world.

// CRITICAL FIX: Add #[macro_use] to the module defining the Godot class.
// This ensures that the helper macros generated by #[derive(GodotClass)] 
// in state.rs are available to all other files in the 'engine' module.
#[macro_use] 
pub mod state;

pub mod init;
pub mod api;
pub mod tick;
pub mod commands;
pub mod query;
pub mod cleanup;
pub mod render_batch;
pub mod query_data;
// FIX: Added the missing public declaration for api_initializers
pub mod api_initializers; 

pub use state::*;
pub use init::*;
pub use api::*;
pub use tick::*;
pub use commands::*;
pub use query::*;
pub use cleanup::*;

// Re-export the Godot class so lib.rs only needs one line
pub use state::SSXLEngine;