// ============================================================================
// 🎼 Chunk Data Query Logic (`crate::engine::query_data`)
// ----------------------------------------------------------------------------
// This module defines the `fetch_chunk_data_logic` function, which provides
// Godot scripts with read-only access to specific chunk data generated by the
// SSXL engine. It acts as a bridge between Rust’s generation API and Godot’s
// scripting layer.
//
// Purpose:
//   • Allow Godot to request structured chunk data by coordinates (x, y).
//   • Provide a safe, side-effect-free query into the engine’s generation API.
//   • Return results in Godot’s native `Dictionary` type for seamless FFI.
//
// Key Components:
//   • SSXLEngine
//       - Core engine struct exposed to Godot.
//       - Holds references to subsystems including the generation API.
//   • state! macro
//       - Provides scoped access to the internal state of `SSXLEngine`.
//       - Expands to code that dereferences the internal state pointer safely.
//   • Dictionary
//       - Godot’s built-in key-value container type.
//       - Used here to return chunk data in a format that Godot scripts can consume.
//
// Function: fetch_chunk_data_logic
//   • Arguments:
//       - engine: mutable reference to `SSXLEngine`.
//         (mutable required because `state!` macro dereferences internal state,
//         even though this function itself does not mutate).
//       - x, y: integer coordinates of the chunk being requested.
//   • Workflow:
//       1. Access engine’s internal state via `state!` macro.
//       2. Call `generation_api.fetch_chunk_data(x, y)`.
//       3. Return the resulting `Dictionary` to Godot.
//   • Returns:
//       - Dictionary containing chunk data (tiles, metadata, etc.).
//       - The exact contents depend on the implementation of `generation_api`.
//
// Design Choices:
//   • Query-only function ensures no mutation or side effects.
//   • Returning `Dictionary` aligns with Godot’s native data structures.
//   • Encapsulation via `generation_api` centralizes data retrieval logic.
//
// Educational Note:
//   • This function demonstrates how Rust can expose safe, read-only queries
//     to external engines like Godot. By combining macro-based state access,
//     structured data containers, and FFI integration, it provides a clean,
//     ergonomic interface for retrieving chunk data in game scripts.
// ============================================================================


use godot::builtin::Dictionary; 
use crate::engine::state as state_module; 
use state_module::{SSXLEngine, state}; 

pub fn fetch_chunk_data_logic(engine: &mut SSXLEngine, x: i32, y: i32) -> Dictionary {
    state!(engine).generation_api.fetch_chunk_data(x, y)
}
