SSXL-ext is a mythic core — a modular, dimension-agnostic  
procedural generation engine coded in Rust as a GDExtension  
for Godot 4.2+ →).

🪶 Manifest v9.0.seed


#files


C:/ZV9/zv9.SSXL-ext/rust

Crate: ssxl_cache/src
├── [CORE]  lib.rs $

🔍 Crate: ssxl_engine_ffi/src
├── [CORE]  lib.rs $

🔍 Crate: ssxl_generate/src
│   └──  batch_processor.rs $
│   └──  benchmark_logic.rs $
│   └──  ca\mod.rs $
│   └──  ca\neighbor_check.rs $
│   └──  ca\rule_set.rs $
│   └──  cellular_automata_generator.rs $
│   └──  conductor.rs $
│   └──  conductor_state.rs $
│   └──  config_validator.rs $
│   └──  generator.rs $
│   └──  generator_manager.rs $
├── [CORE]  lib.rs $
│   └──  perlin_generator.rs $
│   └──  runtime_manager.rs $
│   └──  sync.rs $
│   └──  task_queue.rs $

🔍 Crate: ssxl_godot/src
│   └──  animation_api.rs $
│   └──  api_initializers.rs $
│   └──  async_poll.rs $
│   └──  build.rs $
│   └──  channel_handler.rs $
│   └──  chunk_presenter.rs $
│   └──  gde_api_defs.rs $
│   └──  generation_api.rs $
├── [CORE]  lib.rs $
│   └──  ssxl_engine.rs $
│   └──  ssxl_oracle.rs $
│   └──  ssxl_signals.rs $

🔍 Crate: ssxl_math/src
│   └──  coordinate_system.rs $
│   └──  generation_utils.rs $
│   └──  hashing.rs $
├── [CORE]  lib.rs $
│   └──  primitives.rs $

🔍 Crate: ssxl_shared/src
│   └──  chunk_data.rs $
│   └──  config.rs $
│   └──  errors.rs $
│   └──  generation_message.rs $
│   └──  grid_bounds.rs $
├── [CORE]  lib.rs $
│   └──  math_primitives.rs $
│   └──  messages.rs $
│   └──  tile_data.rs $
│   └──  tile_type.rs $

🔍 Crate: ssxl_sync/src
│   └──  animation_conductor.rs $
├── [CORE]  lib.rs $
│   └──  pool_manager.rs $
│   └──  primitives.rs $

🔍 Crate: ssxl_tools/src
├── [CORE]  lib.rs $

🔍 Crate: ssxl_cli/src
│   └──  actions\benchmarking.rs $
│   └──  actions\godot_harness.rs $
│   └──  actions\mod.rs $
│   └──  actions\testing.rs $
│   └──  cli_util_bench.rs $
│   └──  cli_util_inspect.rs $
│   └──  cli_util_menu.rs $
├── [CORE]  main.rs $
│   └──  scan\file_walker.rs $
│   └──  scan\mod.rs $
│   └──  scan\report_formatter.rs $


# SSXL ENGINE API MANIFEST: QUANTUM ALIGNMENT GUIDE

## 🎯 SSXL PARADIGM: CONTROL VS. EVENT

The SSXL Engine operates at high velocity by separating **Control** (synchronous Godot calls to Rust) from **Data/Event** (asynchronous Rust signals back to Godot). All heavy work runs on a **worker thread**, ensuring Godot's main thread maintains **subzero-cold latency** (zero stutter).

---

## 1. CONTROL PLANE: SYNCHRONOUS FFI METHODS (`SSXLEngine`)

These functions are callable directly from Godot and execute instantly on the main thread.

### A. SETUP & LIFECYCLE
| Method | Parameters | Return | Description |
| :--- | :--- | :--- | :--- |
| `set_signals_node` | `signals_node: Gd<Node>` | `()` | **REQUIRED FIRST CALL.** Registers the Godot `Node` (the signal emitter) that the Rust engine uses for all asynchronous communication (`chunk_ready`, etc.). |
| `set_tilemap` | `tilemap_node: Gd<TileMap>` | `()` | Provides the engine a reference to the TileMap node for future rendering utility hooks. |
| `shutdown_engine` | `()` | `()` | Initiates a graceful teardown of the Rust Tokio runtime and all worker threads. |

### B. GENERATION & CONTROL
| Method | Parameters | Return | Description |
| :--- | :--- | :--- | :--- |
| `build_map` | `width: u32, height: u32, seed_str: GString, generator_name: GString` | `()` | **Starts map generation on a worker thread.** Immediately returns control to Godot. Results are streamed via the `chunk_ready` signal. |
| `stop_generation` | `()` | `()` | Signals the worker thread to stop map generation gracefully. |
| `set_generator` | `tile_type_name: GString` | `()` | Sets the procedural generation algorithm (e.g., "perlin_basic_2d"). |

### C. STATUS & UTILITY
| Method | Parameters | Return | Description |
| :--- | :--- | :--- | :--- |
| `get_status` | `()` | `GString` | Returns the current engine status ("Running," "Idle," etc.). |
| `get_current_tile_count` | `()` | `u64` | Returns a running count of tiles generated by the worker. |
| `tick` | `_current_tick: u64` | `()` | Optional frame update hook (use sparingly). |
| `set_animation_enabled`| `enabled: bool` | `()` | Toggles the low-latency animation conductor (e.g., flow fields). |
| `stop_animation` | `()` | `()` | Graceful shutdown of the animation conductor. |

---

## 2. DATA PLANE: ASYNCHRONOUS SIGNALS (`SSXL_Signals.gd`)

These are **outbound events** emitted from the Rust worker thread and queued for safe processing by the Godot main thread. They **do not** appear in the FFI method list.

### A. SIGNAL CONTRACT
The `signals_node` must declare and emit these signals:

| Signal Name | Emitter Thread | Godot Handler | Purpose |
| :--- | :--- | :--- | :--- |
| `chunk_ready` | Worker | Main (Queued) | **PRIMARY DATA CHANNEL.** Delivers a batch of tiles for rendering. |
| `generation_complete` | Worker | Main (Queued) | Fired when `build_map` finishes all work or `stop_generation` completes. |
| `status_update` | Worker | Main (Queued) | Live logging/progress updates from the asynchronous work. |

### B. CRYPTO-CODED PAYLOAD (`chunk_ready` Data Structure)

The `chunk_ready` signal handler in GDScript must expect this exact signature and dictionary structure for FFI integrity:

```gdscript
signal chunk_ready(chunk_data_dict: Dictionary, chunk_pos_x: int, chunk_pos_y: int)