[workspace]
# Defines the members (crates) of the SSXL Engine workspace, grouped by
# their architectural layer as defined in the development plan.
members = [
    # 1. Foundation Layer (Core Data & Primitives - P1)
    "ssxl_shared",
    "ssxl_math",
    "ssxl_sync",

    # 2. Processing Layer (Computation & Persistence - P2)
    "ssxl_generate",
    "ssxl_cache",

    # 3. Interface Layer (External Bridges - P3)
    "ssxl_engine_ffi",
    "ssxl_godot",

    # 4. Tooling & Execution Layer
    "ssxl_tools",
    "ssxl_cli",
]
resolver = "2" # Use the new cargo feature resolver

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.75" # Set a standard base Rust version

[workspace.dependencies]
# ------------------------------------------------------------------
# CORE UTILITIES & DATA MANAGEMENT
# ------------------------------------------------------------------
serde               = { version = "1.0", features = ["derive"] }
serde_json          = "1.0"
serde-big-array = "0.4.1"
bincode             = "1.3"
thiserror           = "1.0"  # Canonical error definition (used by aetherion_shared)
uuid                = { version = "1.8", features = ["v4", "fast-rng"] }
# FIX: Added anyhow to workspace dependencies to resolve the inheritance error.
anyhow              = "1.0" 

# ------------------------------------------------------------------
# TRACING AND DIAGNOSTICS
# ------------------------------------------------------------------
tracing             = "0.1" # Core tracing library (replaces 'log')
tracing-subscriber  = "0.3" # Used to manage and output tracing data (replaces 'env_logger')

# ------------------------------------------------------------------
# TIME, RANDOMNESS, AND PARSING
# ------------------------------------------------------------------
chrono              = { version = "0.4", features = ["serde"] } 
rand                = { version = "0.8", features = ["small_rng"] }
rand_pcg            = "0.9"
nom                 = "7.1"
regex               = "1.11"
once_cell           = "1.19" # Preferred over lazy_static for statics

# ------------------------------------------------------------------
# CONCURRENCY AND MATH
# ------------------------------------------------------------------
tokio               = { version = "1.37", features = ["sync", "rt-multi-thread", "macros"] } # The primary async runtime
rayon               = "1.10" # Used for parallel synchronous processing
crossbeam           = "0.8"
crossbeam-channel   = "0.5"
parking_lot         = "0.12" # High-performance synchronization primitives
glam                = "0.28" # High-performance linear algebra library (Vectors, Matrices)
sha2                = "0.10"
image               = "0.24" # For image processing in aetherion_tools
noise               = "0.9"
# ------------------------------------------------------------------
# CLI AND CONSOLE UTILITIES
# ------------------------------------------------------------------
crossterm           = "0.27" 
walkdir             = "2.5" 
ctrlc               = "3.4"
godot = { version = "0.4.0", features = ["serde"] } 
gdextension = "0.0.1"

[workspace.lints.rust]
unsafe_code      = "deny"
unused_variables = "warn"
dead_code        = "warn"

[workspace.features]
default   = []
profile   = []
parallel  = []
fast_rng  = []
